// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.731
// web/components/footer.templ

package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<footer class=\"bg-white dark:bg-neutral-800 border-t border-neutral-200 dark:border-neutral-700\"><div class=\"container mx-auto px-4 py-8\"><div class=\"flex flex-col items-center justify-center space-y-4\"><div class=\"flex space-x-6\"><a href=\"https://github.com/amoghyermalkar123\" target=\"#blank\" class=\"text-neutral-500 dark:text-neutral-400 hover:text-neutral-900 dark:hover:text-white\">GitHub</a> <a href=\"https://x.com/curlykoder\" target=\"#blank\" class=\"text-neutral-500 dark:text-neutral-400 hover:text-neutral-900 dark:hover:text-white\">Twitter</a> <a href=\"https://www.youtube.com/@technicaltales\" target=\"#blank\" class=\"text-neutral-500 dark:text-neutral-400 hover:text-neutral-900 dark:hover:text-white\">Youtube</a></div><p class=\"text-neutral-500 dark:text-neutral-400 text-sm\">© 2024 Amogh M. Yermalkar. All rights reserved.</p></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
