// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.731
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"blog-portfolio/internal/models"
	"blog-portfolio/web/components"
	"blog-portfolio/web/layouts"
)

func Home(data layouts.PageData, latestPosts []*models.Post) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" <section class=\"bg-gradient-to-b from-neutral-50 to-white dark:from-neutral-900 dark:to-neutral-800\"><div class=\"max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-20\"><div class=\"text-center\"><h1 class=\"text-4xl font-bold text-neutral-900 dark:text-white sm:text-5xl\">Welcome to My Digital Garden</h1><p class=\"mt-4 text-lg text-neutral-600 dark:text-neutral-300 max-w-2xl mx-auto\">I write about software development, technology, and my journey as a developer. Here you'll find my thoughts, projects, and learnings.</p><div class=\"mt-8 flex justify-center gap-4\"><a href=\"/blog\" class=\"rounded-md bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-primary-500\">Read the Blog</a> <a href=\"https://github.com/yourusername\" target=\"_blank\" class=\"rounded-md bg-neutral-100 dark:bg-neutral-800 px-4 py-2.5 text-sm font-semibold text-neutral-900 dark:text-white hover:bg-neutral-200 dark:hover:bg-neutral-700\">View Projects</a></div></div></div></section> <section class=\"py-16 bg-white dark:bg-neutral-900\"><div class=\"max-w-4xl mx-auto px-4 sm:px-6 lg:px-8\"><div class=\"flex justify-between items-baseline mb-8\"><h2 class=\"text-2xl font-bold text-neutral-900 dark:text-white\">Latest Posts</h2><a href=\"/blog\" class=\"text-primary-600 dark:text-primary-400 hover:text-primary-500\">View all posts →</a></div><div class=\"space-y-8\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, post := range latestPosts {
				templ_7745c5c3_Err = components.PostPreview(post).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if len(latestPosts) == 0 {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"text-center py-12 text-neutral-600 dark:text-neutral-400\">No posts yet. Check back soon!</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></section> <section class=\"py-16 bg-neutral-50 dark:bg-neutral-800\"><div class=\"max-w-4xl mx-auto px-4 sm:px-6 lg:px-8\"><h2 class=\"text-2xl font-bold text-neutral-900 dark:text-white mb-8\">Featured Projects</h2><div class=\"grid gap-8 md:grid-cols-2\"><div class=\"bg-white dark:bg-neutral-900 rounded-lg shadow-sm p-6\"><h3 class=\"text-lg font-semibold text-neutral-900 dark:text-white mb-2\">Project Name</h3><p class=\"text-neutral-600 dark:text-neutral-400 mb-4\">Brief description of the project and what technologies were used.</p><div class=\"flex gap-2\"><a href=\"#\" class=\"text-primary-600 hover:text-primary-500\">View Project →</a></div></div><div class=\"bg-white dark:bg-neutral-900 rounded-lg shadow-sm p-6\"><h3 class=\"text-lg font-semibold text-neutral-900 dark:text-white mb-2\">Another Project</h3><p class=\"text-neutral-600 dark:text-neutral-400 mb-4\">Brief description of another interesting project.</p><div class=\"flex gap-2\"><a href=\"#\" class=\"text-primary-600 hover:text-primary-500\">View Project →</a></div></div></div></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.Base(layouts.PageData{
			Title:       "Home | Blog & Portfolio",
			Description: "Welcome to my personal blog and portfolio",
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
